### PR TITLE
Bump Ruby

### PR DESCRIPTION
**Pull request by nikolai-b**
I've taken a different approach and have used the Brightbox PPA.  This works on a fresh desktop Ubuntu 14.04, @mvl22 can we trial it on a backup server as I'd like to check installing the new version of ruby doesn't cause clashes.  I've also updated the apt cookbook like you asked martin so that we now have the unattended upgrades recipe, from the docs looks like it will keep packages up to date. @gravitystorm any thoughts, I'm still new to chef.

### CODE REVIEW

**Comment by nikolai-b** [comment]
P.S I tried to use https://github.com/mojolingo/brightbox-ruby-cookbook but ran into problems because of newer ruby version trying to read `/etc/gemrc` but on second thoughts maybe I should push that as I'd prefer to use a maintained version.

**Comment by mvl22** [comment]
Can you try on a fresh VM? Create a Virtualbox VM and just roll out to that. cyclescape3 and cyclescape4 should both be considered production so I'm wary of putting anything experimental on that.

**Comment by nikolai-b** [comment]
I can do this on a Fresh VM and it works.  What I can't check is if it works compared to what is currently on cyclescape3 and cyclescape4.

What I have done is:
* create a new VM
* ran the chef script from master (so that the VM is like the production environment)
* switch the chef repo to `brightbox` and set the [revision](https://github.com/cyclestreets/cyclescape-chef/blob/master/cookbooks/cyclescape/recipes/default.rb#L116) to any different SHA (or branch)
* re-ran the chef script

After this everything works as expected and the ruby version has been updated.  If you just re-run the chef script without changing the SHA then the gem's are not installed so this should be rolled out along with an empty commit to the cyclescape reop (to change the master SHA).

**Comment by mvl22** [comment]
Great. What Ruby version is this now?

Will give it a try on cyclescape4.

**Comment by smsm1** [comment]
Would it be possible to for example make a clone of cyclescape4, and then test it on the clone of the vm, thus allowing you to test on a copy of the live system?

**Comment by nikolai-b** [comment]
This is ruby version 2.1.6 but more importantly it is from the brightbox repo so it will be very easy to upgrade it in future, just change https://github.com/cyclestreets/cyclescape-chef/blob/brightbox/cookbooks/brightbox-ruby/attributes/default.rb#L2 to any value from https://launchpad.net/~brightbox/+archive/ubuntu/ruby-ng 
Also they have pre-build passenger gem so we can look at removing  passenger-gem cookbook.

**Comment by mvl22** [comment]
Would you mind adding such a commit (an empty/unimportant commit)?

**Comment by mvl22** [comment]
> thus allowing you to test on a copy of the live system?

cyclescape4 is a copy of the live system, cyclescape3.

**Comment by nikolai-b** [comment]
Sure, as you like your Easter Eggs I've made [nowhere Downing street](https://github.com/cyclestreets/cyclescape/commit/d896c0ab927f007c72e5daab54c6f81e9fb7e439).

**Comment by mvl22** [comment]
Thanks for that change; very appropriate given the election result.

Does seem to have worked on my local VM.

Could you put the brightbox stuff into master and I'll roll out on cyclescape4 then cyclescape3.

**Comment by mvl22** [comment]
Thanks; now rolled out fine on cyclescape3 and cyclescape4.

**Comment by mvl22** [comment]
Is this two-month-old branch now obsolete?

https://github.com/cyclestreets/cyclescape/tree/ruby_version

**Comment by nikolai-b** [comment]
Yep, deleted

**Pull request merged**
